/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreasuriesRouteImport } from './routes/treasuries'
import { Route as NationsRouteImport } from './routes/nations'
import { Route as InstitutionalRouteImport } from './routes/institutional'
import { Route as BanksRouteImport } from './routes/banks'
import { Route as IndexRouteImport } from './routes/index'

const TreasuriesRoute = TreasuriesRouteImport.update({
  id: '/treasuries',
  path: '/treasuries',
  getParentRoute: () => rootRouteImport,
} as any)
const NationsRoute = NationsRouteImport.update({
  id: '/nations',
  path: '/nations',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalRoute = InstitutionalRouteImport.update({
  id: '/institutional',
  path: '/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksRoute = BanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banks': typeof BanksRoute
  '/institutional': typeof InstitutionalRoute
  '/nations': typeof NationsRoute
  '/treasuries': typeof TreasuriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banks': typeof BanksRoute
  '/institutional': typeof InstitutionalRoute
  '/nations': typeof NationsRoute
  '/treasuries': typeof TreasuriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banks': typeof BanksRoute
  '/institutional': typeof InstitutionalRoute
  '/nations': typeof NationsRoute
  '/treasuries': typeof TreasuriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/banks' | '/institutional' | '/nations' | '/treasuries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/banks' | '/institutional' | '/nations' | '/treasuries'
  id:
    | '__root__'
    | '/'
    | '/banks'
    | '/institutional'
    | '/nations'
    | '/treasuries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BanksRoute: typeof BanksRoute
  InstitutionalRoute: typeof InstitutionalRoute
  NationsRoute: typeof NationsRoute
  TreasuriesRoute: typeof TreasuriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treasuries': {
      id: '/treasuries'
      path: '/treasuries'
      fullPath: '/treasuries'
      preLoaderRoute: typeof TreasuriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nations': {
      id: '/nations'
      path: '/nations'
      fullPath: '/nations'
      preLoaderRoute: typeof NationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional': {
      id: '/institutional'
      path: '/institutional'
      fullPath: '/institutional'
      preLoaderRoute: typeof InstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks': {
      id: '/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof BanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BanksRoute: BanksRoute,
  InstitutionalRoute: InstitutionalRoute,
  NationsRoute: NationsRoute,
  TreasuriesRoute: TreasuriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
